# Generated by Django 4.2.7 on 2026-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('upcoming', 'Предстоящий платеж'), ('overdue', 'Просрочка платежа'), ('price_increase', 'Повышение цены'), ('inactive', 'Неактивность'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('recommendation', 'Рекомендация')], max_length=20),
        ),
    ]
