# Generated by Django 4.2.7 on 2026-02-27 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("yandex", "Yandex"),
                            ("mailru", "Mail.ru"),
                            ("outlook", "Outlook"),
                            ("other", "Другой"),
                        ],
                        max_length=20,
                    ),
                ),
                ("imap_server", models.CharField(blank=True, max_length=255)),
                ("imap_port", models.IntegerField(default=993)),
                ("password_encrypted", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("check_frequency", models.IntegerField(default=60)),
                ("search_folder", models.CharField(default="INBOX", max_length=100)),
                (
                    "search_criteria",
                    models.TextField(
                        default='FROM "noreply" OR FROM "billing" OR SUBJECT "subscription" OR SUBJECT "payment"'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "email")},
            },
        ),
        migrations.CreateModel(
            name="ParsedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=500, unique=True)),
                ("subject", models.CharField(max_length=500)),
                ("from_email", models.EmailField(max_length=254)),
                ("received_date", models.DateTimeField()),
                ("service_name", models.CharField(blank=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("raw_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_emails",
                        to="mail_parser.mailbox",
                    ),
                ),
                (
                    "processed_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date"],
                "indexes": [
                    models.Index(
                        fields=["mailbox", "is_processed"],
                        name="mail_parser_mailbox_517336_idx",
                    )
                ],
            },
        ),
    ]
